### ISSUE TITLE
[Frontend] Collapsed space/kerning issue in artist name (breadcrumb nav)

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#15]
<img width="1807" alt="breadcrumb_text_fiona" src="https://user-images.githubusercontent.com/37549099/38268596-56364944-3733-11e8-8606-a31271207185.png">

**Comment by owenhoskins** [comment]
Good catch, this is actually a ligature but it's hard to see at that size with the blur and does look like a bug. I've just worked out how to disable that feature.

![screen shot 2018-04-11 at 4 14 11 pm](https://user-images.githubusercontent.com/1849997/38618870-7c16160a-3da3-11e8-89ee-896bf90f9d0d.png)
![screen shot 2018-04-11 at 4 14 01 pm](https://user-images.githubusercontent.com/1849997/38618871-7c373c2c-3da3-11e8-9b2a-3660ea8c8518.png)

![screen shot 2018-04-11 at 4 05 09 pm](https://user-images.githubusercontent.com/1849997/38618634-eb1b0610-3da2-11e8-9efb-021c1b3c3dd8.png)
