### ISSUE TITLE
[Front End] Services Page > Click faded text to read next service 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#16]
User can see the next copy description (faded out), but either has to scroll or click nav to reach copy. User should be able to click (or swipe) on faded text to get to next service. 

![apr-3-2018-11_33-am](https://user-images.githubusercontent.com/37549099/38268685-9ac0f424-3733-11e8-900d-bf2353b9a8f3.gif)

**Comment by owenhoskins** [comment]
This makes sense. Will look into it when I revisit the mouse scrolling behavior!

**Comment by owenhoskins** [comment]
Closing in favor of #76.
