### ISSUE TITLE
[Front End] Artist Roster Nav > Hover x roster name animation

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#17]
User can hover over various rosters, but has to physically click roster nav to reach full roster (hair, makeup, styling).

 As a user if I am able to hover over makeup artists names, I want the full roster to fade into view (nav category changes, but animation / full view of roster does not move with nav).

 There are no obvious rollovers/hover for Artist names which is confusing. I think that by clicking over the "makeup roster" it will show me the full roster, but actually takes me to an artist portfolio. 

![apr 3 2018 11_41 am](https://user-images.githubusercontent.com/37549099/38269441-5e010374-3735-11e8-998f-ff69694f3bf4.gif)

**Comment by owenhoskins** [comment]
Closing in favor of #76.
