### ISSUE TITLE
[Backend] Please include the option to resequence the order in which Services appear

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#23]

**Comment by swartists** [comment]
<img width="1822" alt="screen shot 2018-04-03 at 12 37 45 pm" src="https://user-images.githubusercontent.com/37549099/38271633-d3713736-373b-11e8-81c8-907d2d7581eb.png">

**Comment by owenhoskins** [comment]
![screen shot 2018-04-06 at 12 13 11 pm](https://user-images.githubusercontent.com/1849997/38413293-eb86f0ae-3993-11e8-833b-f1573256f611.png)
