### ISSUE TITLE
[Frontend] Videos: can we include the capability to manually adjust the thumbnail aspect in order to make appearance consistent?

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#24]
<img width="1747" alt="screen shot 2018-04-03 at 12 47 37 pm" src="https://user-images.githubusercontent.com/37549099/38272197-64a746a4-373d-11e8-9c8c-221a13f46022.png">

**Comment by swartists** [comment]
<img width="1901" alt="screen shot 2018-04-03 at 1 06 35 pm" src="https://user-images.githubusercontent.com/37549099/38273072-e0e5bf14-373f-11e8-8269-7dbddcbcb8d1.png">

**Comment by swartists** [comment]
<img width="1910" alt="screen shot 2018-04-03 at 1 07 10 pm" src="https://user-images.githubusercontent.com/37549099/38273088-f1df670c-373f-11e8-926e-49c48e0e1086.png">

**Comment by owenhoskins** [comment]
Just tested this and yes you can control the ratio by setting it in the CMS for that video item. Please note that the video will be "letter-boxed" as a result and there is no way to have both the poster image matching the other videos and video without a letterbox if the video itself has a different ratio.

![screen shot 2018-04-06 at 1 45 39 pm](https://user-images.githubusercontent.com/1849997/38417443-fb323a74-39a0-11e8-9656-6a19e282d662.png)
![screen shot 2018-04-06 at 1 48 03 pm](https://user-images.githubusercontent.com/1849997/38417483-2bfd184a-39a1-11e8-8da6-471254357acc.png)

**Comment by swartists** [comment]
I’m ok with the video being letterboxed while playing as long as the poster images are consistent. Thanks Owen


Beth Hancock
Head of Digital Content | Web/Creative

SWA
1601 Vine Street
Los Angeles, CA 90028

T  +1 424 704 2466
C +1 917 446 0451

www.starworksartists.com
instagram.com/starworksartists
