### ISSUE TITLE
[Backend/Frontend] Artist name in breadcrumb nav needs to match header

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#38]

**Comment by swartists** [comment]
<img width="2153" alt="screen shot 2018-04-03 at 1 54 54 pm" src="https://user-images.githubusercontent.com/37549099/38275458-c6b60cdc-3746-11e8-85f2-db96ea32aff5.png">
 include hyphens and accents where appropriate.

**Comment by owenhoskins** [comment]
Fixed!
