### ISSUE TITLE
[Front End] Artist Roster Nav > Stylist

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#39]
When user is on special bookings, manicurist or grooming and hovers over general background, "stylist" becomes highlighted even though no stylists are present on screen

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/37549099/38275500-ed3eb692-3746-11e8-814f-0e76189d677b.gif)

**Comment by owenhoskins** [comment]
Closing in favor of #76.
