### ISSUE TITLE
[Frontend] Performance portfolios (CCN and JCL) and manicurist red carpet (DLN) should follow same image balancing as stylist red carpet 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#53]
<img width="2160" alt="screen shot 2018-04-03 at 4 42 49 pm" src="https://user-images.githubusercontent.com/37549099/38281209-51b07b1c-375e-11e8-945c-932dc28c6ace.png">

![screen-shot-2018-04-03-at-4 44 24-pm](https://user-images.githubusercontent.com/37549099/38281214-5a876138-375e-11e8-9bd4-607f2e69bdad.jpg)

**Comment by owenhoskins** [comment]
Just realized why DLN and JCL weren't like the Stylist Red Carpet, for those I have already set the "columns" field to 6, like so:

![screen shot 2018-04-11 at 3 54 35 pm](https://user-images.githubusercontent.com/1849997/38617904-d776a5a8-3da0-11e8-8586-ad20800e6c27.png)
