### ISSUE TITLE
[Backend] Add bullet fields to Services sections

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#56]
<img width="2182" alt="screen shot 2018-04-04 at 11 01 03 am" src="https://user-images.githubusercontent.com/37549099/38325314-7f787dbc-37f7-11e8-8aef-7eed59a609fa.png">

**Comment by owenhoskins** [comment]
![screen shot 2018-04-06 at 12 13 11 pm](https://user-images.githubusercontent.com/1849997/38413293-eb86f0ae-3993-11e8-833b-f1573256f611.png)

![screen shot 2018-04-06 at 12 43 41 pm](https://user-images.githubusercontent.com/1849997/38414782-2fe318fa-3998-11e8-962c-da0dcdcd94a0.png)

We still need to test the style for the bullet points but now we can experiment with the text content!
