### ISSUE TITLE
[Front End] Safari 11.03 | Breadcrumbs, email agent, instagram type cut off

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#57]
<img width="807" alt="screen shot 2018-04-04 at 3 22 21 pm" src="https://user-images.githubusercontent.com/37549099/38337930-3594a624-381c-11e8-9e3c-65f7f4eaad2d.png">

<img width="417" alt="screen shot 2018-04-04 at 3 22 14 pm" src="https://user-images.githubusercontent.com/37549099/38337934-380d30ce-381c-11e8-9b29-5f087b96d5a1.png">

**Comment by owenhoskins** [comment]
Strange -- I can not reproduce this with Safari 11.0.2. Tried resizing the browser a bunch. I am missing something?

![screen shot 2018-04-05 at 8 06 48 pm](https://user-images.githubusercontent.com/1849997/38380630-f61543cc-390c-11e8-9774-5c056c024f7a.png)

**Comment by owenhoskins** [comment]
Ok. Closing, reopen the issue if you can reproduce.

**Comment by swartists** [comment]
We couldn’t reproduce. Seems fixed for now. Thank you!


Beth Hancock
Head of Digital Content | Web/Creative

SWA
1601 Vine Street
Los Angeles, CA 90028

T  +1 424 704 2466
C +1 917 446 0451

www.starworksartists.com
instagram.com/starworksartists
