### ISSUE TITLE
[Front End] Services Page > Mouse Scroll 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#6]
User has the capability to scroll through services, but nav does not scroll at the same pace as the descriptions. 

User can scroll all the way through to the point where no text is visible 

![apr-3-2018-11_19-am](https://user-images.githubusercontent.com/37549099/38267728-297c8028-3731-11e8-8c46-04961fd02451.gif)

**Comment by owenhoskins** [comment]
Closing in favor of #76.
