### ISSUE TITLE
[Front End] Artists > Scroll through rosters 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#60]
User is able to scroll through artist rosters, art roster nav does not reflect scroll and once user reaches stylists, grooming,  manicurist or special bookings nav and names roster becomes wonky

![apr-4-2018-3_35-pm](https://user-images.githubusercontent.com/37549099/38338520-c55139e2-381e-11e8-8132-98a19b2f3fd2.gif)

**Comment by owenhoskins** [comment]
Closing in favor of #76.
