### ISSUE TITLE
[Front End] Artist Roster > Page Load > Additional Scroll Element 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#62]
When user clicks onto Artist roster an additional scroll element appears (right hand side) while page is loading 

![apr-4-2018-3_54-pm](https://user-images.githubusercontent.com/37549099/38338965-aee19b96-3820-11e8-8bf4-773825bb7fc2.gif)

**Comment by owenhoskins** [comment]
Can't reproduce. Please reopen if you can!

**Comment by swartists** [comment]
Can no longer reproduce
