### ISSUE TITLE
[Front End] Artist Page > Instagram, email agent appearing in transition to cover photo, artist nav not appearing correctly 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#63]
When user clicks into Artist page, the transition shows the instagram/email agent incorrectly in top left 

Artist nav also shows incorrectly when revisiting artist portfolio page

[Apr-4-2018-4_06-PM.gif.zip](https://github.com/swartists/starworksartists.com/files/1878101/Apr-4-2018-4_06-PM.gif.zip)

**Comment by owenhoskins** [comment]
Can't reproduce, please reopen if you can!

**Comment by swartists** [comment]
Can no longer reproduce
