### ISSUE TITLE
[Frontend] Services: Could we create a bit more space/expanse in the text...

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#65]
<img width="1906" alt="screen shot 2018-04-05 at 3 45 31 pm" src="https://user-images.githubusercontent.com/37549099/38395560-681bff44-38e8-11e8-8355-93e7b03c1dcd.png">
It feels packed very tightly, wondering if there is a way to create a bit of visual breathing room in the text presentation

**Comment by owenhoskins** [comment]
![screen shot 2018-04-06 at 12 43 41 pm](https://user-images.githubusercontent.com/1849997/38415590-a53dd39a-399a-11e8-83ba-77e28c3794b4.png)
