### ISSUE TITLE
[Front End] Artist Portfolio Nav > breaking points

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#68]
Breaking points for Artist portfolio nav are wonky. When user resizes window, nav moves to top of page and space in between each category is too great. User has trouble navigating portfolio

![apr-6-2018-9_58-am](https://user-images.githubusercontent.com/37549099/38434025-d1f2d67e-3981-11e8-8f4d-cff6d17ef374.gif)

**Comment by owenhoskins** [comment]
Closing in favor of #71.

**Comment by owenhoskins** [comment]
Closing in favor of #71.
