### ISSUE TITLE
[Frontend/Backend] API not pulling information from Vimeo for Sami Knight's videos

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#69]
I've double checked that the codes are correct. Please advise...
<img width="1673" alt="screen shot 2018-04-06 at 10 12 51 am" src="https://user-images.githubusercontent.com/37549099/38434438-2e00a8e6-3983-11e8-8cea-2151da0db1ca.png">

**Comment by owenhoskins** [comment]
![screen shot 2018-04-10 at 4 28 55 pm](https://user-images.githubusercontent.com/1849997/38561391-95893d4c-3ce0-11e8-986a-7a8031f36f0e.png)

It worked for me. There is a limit of 200 requests to the Vimeo API within a 15 minute window but I'd be surprised if you managed to hit that!
