### ISSUE TITLE
[Front End] Services Page > Breaking points 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#8]
Breaking points are wonky: main nav icon floats and animates incorrectly, text resizes incorrectly, services nav disappears, text overlaps nav 

![apr-3-2018-10_58-am](https://user-images.githubusercontent.com/37549099/38266856-9bfdd776-372e-11e8-8d41-daa48e9fc2ec.gif)

**Comment by owenhoskins** [comment]
This is the "Mobile/Tablet" breakpoint where the layout readjusts entirely for portrait format screens. I'll look at how to make that transition more elegant.

**Comment by owenhoskins** [comment]
Closing in favor of #71.
