### ISSUE TITLE
[Front End] Services Page Nav > Animation 

### ISSUE THREAD

**Issue by swartists** [swartists/starworksartists.com#9]
Animation is applied to all nav sub categories, moves up and down until reaches selection. Should only be applied to "clicked" selection 

![apr-3-2018-11_04-am](https://user-images.githubusercontent.com/37549099/38267277-ce010bc0-372f-11e8-8c60-097169389a36.gif)

**Comment by owenhoskins** [comment]
Fixed by 0933b6c
